## **Notebook containing scripts and outputs of the training, cross-validation and empirical data prediction for the *Drosophila* dataset**
From the manuscript Perez et al. "Species Delimitation Meets Deep Learning: Insights from a Highly Fragmented Cactus System"

In [ ]:
#mount google drive to load files
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Import all required modules.
import numpy as np
import pandas as pd
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Input, Activation, Dense, Dropout, Flatten, concatenate
from keras.layers import Conv1D, MaxPooling1D, AveragePooling1D
from keras.models import Model
from tensorflow.keras import regularizers
from keras import backend as K
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from random import shuffle, choice

# Define parameters for the CNN run.
batch_size = 250
epochs = 250
num_classes = 2

# Define the CNN architecture.
def create_cnn(xtest, regularizer=None):
	inputShape = (xtest.shape[1], xtest.shape[2])
	inputs = Input(shape=inputShape)
	x = inputs
	x = Conv1D(250, kernel_size=2, activation='relu',input_shape=(xtest.shape[1], xtest.shape[2]))(x)
	x = Conv1D(125, kernel_size=2, activation='relu')(x)
	x = AveragePooling1D(pool_size=2)(x)
	x = Dropout(0.75)(x)
	x = Conv1D(125, kernel_size=2, activation='relu')(x)
	x = AveragePooling1D(pool_size=2)(x)
	x = Dropout(0.75)(x)
	x = Flatten()(x)
	x = Dense(125, activation='relu')(x)
	x = Dropout(0.5)(x)
	x = Dense(125, activation='relu')(x)
	x = Dropout(0.5)(x)
  # The final fully-connected layer head will have a softmax dense layer
	x = Dense(num_classes, activation="softmax")(x)

	# Construct the CNN
	model = Model(inputs, x)
	# Return the CNN
	return model

# **Train a network for each species pair with 10,000 simulations from each model**
Here we will use the full simulated dataset to train the network, by splitting the data with 75% of simulations for training and 25% for validation.

In [ ]:
################################################################################################################################################
#Train a network using 10K simulations per model for the D.melanogaster-D.sechellia pair.
################################################################################################################################################
# Load Numpy arrays containing simulations.
u1 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/trainingSims/Drosophila/melano_sechellia/simModel1.npz")
u2 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/trainingSims/Drosophila/melano_sechellia/simModel2.npz")
u1 = u1["simModel1"]
u2 = u2["simModel2"]
x=np.concatenate((u1,u2),axis=0)

# Label each simulated array.
y=[0 for i in range(len(u1))]
y.extend([1 for i in range(len(u2))])
y = np.array(y)

#Convert major allele to 0 and minor allele to 1
for arr,array in enumerate(x):
  for idx,row in enumerate(array):
    if np.count_nonzero(row) > len(row)/2:
      x[arr][idx][x[arr][idx] == 0] = -1
      x[arr][idx][x[arr][idx] == 1] = 0
      x[arr][idx][x[arr][idx] == -1] = 1
x=x.astype(np.uint8)

# Print label and simulations length, these should be the same.
print (len(x), len(y))

shf = list(range(len(x)))
shuffle(shf)
y = y[shf]
x = x[shf]

# Separate train (75%) and validate (25%) sets.
xtrain, xtest = x[int(len(y)*.25):], x[:int(len(y)*.25)]
ytrain, ytest = y[int(len(y)*.25):], y[:int(len(y)*.25)]
ytest = keras.utils.to_categorical(ytest, num_classes)
ytrain = keras.utils.to_categorical(ytrain, num_classes)

# Create the CNN network, using the architecture defined above.
cnn = create_cnn(xtest)

# Compile the CNN.
cnn.compile(loss=keras.losses.categorical_crossentropy,
	              optimizer=keras.optimizers.Adam(),
	              metrics=['accuracy'])
print(cnn.summary())

# Run the CNN and save the model with the best val_accuracy. Record the runtime required to train the network
mcp_save = ModelCheckpoint('/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/Trained_10KSims_melano_sechellia.acc.mod', save_best_only=True, monitor='val_accuracy', mode='max')
reduce_lr_loss = ReduceLROnPlateau(monitor='val_accuracy', factor=0.2, patience=20, verbose=1, mode='max')
cnn.fit(xtrain, ytrain, batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(xtest, ytest),callbacks=[mcp_save,reduce_lr_loss])

20000 20000
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 185, 5)]          0         
_________________________________________________________________
conv1d (Conv1D)              (None, 184, 250)          2750      
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 183, 125)          62625     
_________________________________________________________________
average_pooling1d (AveragePo (None, 91, 125)           0         
_________________________________________________________________
dropout (Dropout)            (None, 91, 125)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 90, 125)           31375     
_________________________________________________________________
average_pooling1d_1 (Average (None, 45, 12

In [ ]:
################################################################################################################################################
#Train a network using 10K simulations per model for the D.melanogaster-D.sechellia pair.
################################################################################################################################################
# Load Numpy arrays containing simulations.
u1 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/trainingSims/Drosophila/melano_simulans/simModel1.npz")
u2 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/trainingSims/Drosophila/melano_simulans/simModel2.npz")
u1 = u1["simModel1"]
u2 = u2["simModel2"]
x=np.concatenate((u1,u2),axis=0)
# Label each simulated array.
y=[0 for i in range(len(u1))]
y.extend([1 for i in range(len(u2))])
y = np.array(y)

#Convert major allele to 0 and minor allele to 1
for arr,array in enumerate(x):
  for idx,row in enumerate(array):
    if np.count_nonzero(row) > len(row)/2:
      x[arr][idx][x[arr][idx] == 0] = -1
      x[arr][idx][x[arr][idx] == 1] = 0
      x[arr][idx][x[arr][idx] == -1] = 1
x=x.astype(np.uint8)

# Print label and simulations length, these should be the same.
print (len(x), len(y))

shf = list(range(len(x)))
shuffle(shf)
y = y[shf]
x = x[shf]

# Separate train (75%) and validate (25%) sets.
xtrain, xtest = x[int(len(y)*.25):], x[:int(len(y)*.25)]
ytrain, ytest = y[int(len(y)*.25):], y[:int(len(y)*.25)]
ytest = keras.utils.to_categorical(ytest, num_classes)
ytrain = keras.utils.to_categorical(ytrain, num_classes)

# Create the CNN network, using the architecture defined above.
cnn = create_cnn(xtest)

# Compile the CNN.
cnn.compile(loss=keras.losses.categorical_crossentropy,
	              optimizer=keras.optimizers.Adam(),
	              metrics=['accuracy'])
print(cnn.summary())

# Run the CNN and save the model with the best val_accuracy. Record the runtime required to train the network
mcp_save = ModelCheckpoint('/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/Trained_10KSims_melano_simulans.acc.mod', save_best_only=True, monitor='val_accuracy', mode='max')
reduce_lr_loss = ReduceLROnPlateau(monitor='val_accuracy', factor=0.2, patience=20, verbose=1, mode='max')
cnn.fit(xtrain, ytrain, batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(xtest, ytest),callbacks=[mcp_save,reduce_lr_loss])


20000 20000
Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 108, 6)]          0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 107, 250)          3250      
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 106, 125)          62625     
_________________________________________________________________
average_pooling1d_2 (Average (None, 53, 125)           0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 53, 125)           0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 52, 125)           31375     
_________________________________________________________________
average_pooling1d_3 (Average (None, 26, 12

In [ ]:
################################################################################################################################################
#Evaluate the trained CNN for the D.melanogaster-D.sechellia pair using 1,000 simulations per model as test set.
################################################################################################################################################
# Load Numpy arrays containing test set simulations.
t1 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/TestData/Drosophila/melano_sechellia/simModel1.npz")
t2 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/TestData/Drosophila/melano_sechellia/simModel2.npz")
t1 = t1["simModel1"]
t2 = t2["simModel2"]
t=np.concatenate((t1,t2),axis=0)

#Convert major allele to 0 and minor allele to 1
for arr,array in enumerate(t):
  for idx,row in enumerate(array):
    if np.count_nonzero(row) > len(row)/2:
      t[arr][idx][t[arr][idx] == 0] = -1
      t[arr][idx][t[arr][idx] == 1] = 0
      t[arr][idx][t[arr][idx] == -1] = 1
t=t.astype(np.uint8)

# Label simulations from the test set.
y=[0 for i in range(len(t1))]
y.extend([1 for i in range(len(t2))])
y = np.array(y)

# Load the trained model.
from keras.models import load_model
from sklearn.metrics import confusion_matrix
model = load_model('/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/Trained_10KSims_melano_sechellia.acc.mod')

# Predict and export a confusion matrix.
pred = model.predict(t)
pred_cat = [i.argmax() for i in pred]
print (confusion_matrix(y, pred_cat))

[[879 121]
 [187 813]]


In [ ]:
################################################################################################################################################
#Evaluate the trained CNN for the D.melanogaster-D.simulans pair using 1,000 simulations per model as test set.
################################################################################################################################################
# Load Numpy arrays containing test set simulations.
t1 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/TestData/Drosophila/melano_simulans/simModel1.npz")
t2 = np.load("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/TestData/Drosophila/melano_simulans/simModel2.npz")
t1 = t1["simModel1"]
t2 = t2["simModel2"]
t=np.concatenate((t1,t2),axis=0)

#Convert major allele to 0 and minor allele to 1
for arr,array in enumerate(t):
  for idx,row in enumerate(array):
    if np.count_nonzero(row) > len(row)/2:
      t[arr][idx][t[arr][idx] == 0] = -1
      t[arr][idx][t[arr][idx] == 1] = 0
      t[arr][idx][t[arr][idx] == -1] = 1
t=t.astype(np.uint8)

# Label simulations from the test set.
y=[0 for i in range(len(t1))]
y.extend([1 for i in range(len(t2))])
y = np.array(y)

# Load the trained model.
from keras.models import load_model
from sklearn.metrics import confusion_matrix
model = load_model('/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/Trained_10KSims_melano_simulans.acc.mod')

# Predict and export a confusion matrix.
pred = model.predict(t)
pred_cat = [i.argmax() for i in pred]
print (confusion_matrix(y, pred_cat))

[[783 217]
 [145 855]]


In [ ]:
################################################################################################################################################
#Predict the mos likely model for the empirical data, using the CNN trained with 10K simulations per model.
################################################################################################################################################
# Load the trained network.
model = load_model('/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/Trained_10KSims_melano_sechellia.acc.mod')
# Load empirical data and transpose it.
infile=np.loadtxt("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/input_melano_sechellia.txt")
inp=[]
inp.append(np.array(infile).T)
inp = np.array(inp)

#Convert major allele to 0 and minor allele to 1
for idx,row in enumerate(inp[0]):
  if np.count_nonzero(row) > len(row)/2:
    inp[0][idx][inp[0][idx] == 0] = -1
    inp[0][idx][inp[0][idx] == 1] = 0
    inp[0][idx][inp[0][idx] == -1] = 1
inp=inp.astype(np.uint8)

# Predict the most likely model.
pred = model.predict(inp)
print(pred)

[[0.05142106 0.94857895]]


In [ ]:
################################################################################################################################################
#Predict the mos likely model for the empirical data, using the CNN trained with 10K simulations per model.
################################################################################################################################################
# Load the trained network.
model = load_model('/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/Trained_10KSims_melano_simulans.acc.mod')
# Load empirical data and transpose it.
infile=np.loadtxt("/content/drive/MyDrive/Colab Notebooks/CNN_SpDelimitation_Piloso/input_melano_simulans.txt")
inp=[]
inp.append(np.array(infile).T)
inp = np.array(inp)

#Convert major allele to 0 and minor allele to 1
for idx,row in enumerate(inp[0]):
  if np.count_nonzero(row) > len(row)/2:
    inp[0][idx][inp[0][idx] == 0] = -1
    inp[0][idx][inp[0][idx] == 1] = 0
    inp[0][idx][inp[0][idx] == -1] = 1
inp=inp.astype(np.uint8)

# Predict the most likely model.
pred = model.predict(inp)
print(pred)

[[0.00754976 0.99245024]]
